# Generated by Django 5.0.13 on 2025-12-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('contacto_principal', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('direccion_servicio', models.CharField(max_length=255)),
                ('tipo_negocio', models.CharField(max_length=100)),
                ('fecha_inicio_contrato', models.DateField()),
                ('estado_contrato', models.CharField(max_length=50)),
                ('frecuencia_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario_hora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('turno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('certificaciones_seguridad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('stock_actual', models.IntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('id_proveedor', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_material', models.CharField(max_length=50)),
                ('ubicacion_almacen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo_estandar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada_horas', models.IntegerField()),
                ('productos_usados', models.TextField()),
                ('requiere_equipo_especial', models.BooleanField(default=False)),
                ('categoria_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado_servicio', models.CharField(max_length=50)),
                ('observaciones_cliente', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.clientelimpieza')),
                ('id_empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empleadolimpieza')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.serviciolimpieza')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('impuestos_aplicados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.clientelimpieza')),
                ('id_programacion_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.programacionservicio')),
            ],
        ),
        migrations.CreateModel(
            name='UsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comentarios_uso', models.TextField()),
                ('id_empleado_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empleadolimpieza')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.materiallimpieza')),
                ('id_programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.programacionservicio')),
            ],
        ),
    ]
