# Generated by Django 5.0.13 on 2025-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadolimpieza',
            name='cargo',
            field=models.CharField(default='Sin Cargo', max_length=100),
        ),
    ]
