# Generated by Django 5.0.13 on 2025-12-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_empleadolimpieza_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadolimpieza',
            name='cargo',
        ),
    ]
