# Generated by Django 5.0.13 on 2025-12-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0003_remove_empleadolimpieza_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionservicio',
            name='fecha_programada',
            field=models.DateField(),
        ),
    ]
